import streamlit as st
from diffusers import StableDiffusionPipeline
import torch

# Streamlit App
st.title("AI-Powered Marketing Poster Generator")

def generate_images_using_huggingface_diffusers(text):
    # Load the pre-trained model directly from diffusers
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
    #pipe = pipe.to("cuda")  # Ensure it's using GPU if available

    # Generate the image based on the text prompt
    prompt = text
    image = pipe(prompt).images[0]
    return image

# Streamlit UI to get user input for image generation
input_prompt = st.text_input("Enter your text prompt:")
if input_prompt:
    if st.button("Generate Image"):
        st.write("Generating image.....")
        image_output = generate_images_using_huggingface_diffusers(input_prompt)
        st.success("Image Generated Successfully")
        st.image(image_output, caption="Generated by Huggingface Diffusers")
